-- =============================================================================
-- Cheat Sheet — Quick reference floating window (<leader>?)
-- =============================================================================
--
-- Opens a searchable, scrollable cheat sheet in a floating window.
-- Designed for someone learning Neovim from scratch.
-- =============================================================================

local cheatsheet_lines = {
  "╔══════════════════════════════════════════════════════════════════════════╗",
  "║                     NEOVIM & TMUX CHEAT SHEET                         ║",
  "║               Press q or <Esc> to close · / to search                 ║",
  "╚══════════════════════════════════════════════════════════════════════════╝",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  THE ABSOLUTE BASICS (you need these to survive)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "  MODES — Neovim has modes. This is the #1 concept.",
  "    Normal mode   You're here when you open nvim. Navigate & run commands.",
  "    Insert mode   Where you type text. Press i to enter, jk or Esc to leave.",
  "    Visual mode   Select text. Press v (chars), V (lines), Ctrl+v (block).",
  "    Command mode  Press : to type commands at the bottom.",
  "",
  "  OPENING & CLOSING FILES",
  "    :w              Save current file",
  "    :q              Quit (fails if unsaved changes)",
  "    :wq             Save and quit",
  "    :q!             Quit WITHOUT saving (force)",
  "    <leader>w       Save current file          (Space then w)",
  "    <leader>q       Quit                       (Space then q)",
  "    <leader>bd      Close current file/buffer   (Space then b then d)",
  "",
  "  ⚠ Don't press q alone! That starts macro recording.",
  "    If you accidentally hit q, press q again to stop, then use :q to quit.",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  MOVEMENT (Normal mode — no prefix needed)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    h j k l         Left, Down, Up, Right (or use arrow keys)",
  "    w / b            Next word / Previous word",
  "    0 / $            Start / End of line",
  "    gg / G           Top / Bottom of file",
  "    Ctrl+d / Ctrl+u  Half-page down / up (cursor stays centered)",
  "    { / }            Previous / Next paragraph",
  "    %               Jump to matching bracket",
  "    s + 2 chars      Flash jump (type 2 chars to jump anywhere visible)",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  EDITING (Normal mode)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "  ENTERING INSERT MODE",
  "    i / a            Insert before / after cursor",
  "    I / A            Insert at start / end of line",
  "    o / O            New line below / above",
  "",
  "  DELETING",
  "    x               Delete character under cursor",
  "    dd              Delete entire line",
  "    dw              Delete word",
  "    D               Delete to end of line",
  "",
  "  CHANGING (delete + enter insert mode)",
  "    cw              Change word",
  "    cc              Change entire line",
  "    C               Change to end of line",
  "    ci\"             Change inside quotes (also ci' ci( ci{ ci[)",
  "",
  "  COPY & PASTE",
  "    yy              Copy (yank) current line",
  "    Y               Copy to end of line",
  "    p / P            Paste after / before cursor",
  "    <leader>p        Paste without losing clipboard (visual mode)",
  "",
  "  UNDO & REDO",
  "    u               Undo",
  "    Ctrl+r          Redo",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  FINDING THINGS (Telescope — fuzzy finder)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    <leader>ff       Find files           (Space f f)",
  "    <leader>fg       Live grep (search)   (Space f g)",
  "    <leader>fb       Open buffers         (Space f b)",
  "    <leader>fr       Recent files         (Space f r)",
  "    <leader>fw       Grep word at cursor  (Space f w)",
  "    <leader>/        Search in current file",
  "    <leader>fk       Search all keymaps   (Space f k)",
  "    <leader>fh       Search help          (Space f h)",
  "",
  "  Inside Telescope:",
  "    Ctrl+j / Ctrl+k  Move selection down / up",
  "    Enter            Open file",
  "    Ctrl+s           Open in horizontal split",
  "    Ctrl+q           Send results to quickfix list",
  "    Esc              Close picker",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  FILE EXPLORER & FAST SWITCHING",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "  NEO-TREE (file explorer)",
  "    <leader>n        Toggle file tree     (Space n)",
  "    <leader>N        Reveal current file in tree",
  "    l / Enter        Open file (in tree)",
  "    h               Close folder (in tree)",
  "    a               Create new file (in tree)",
  "    d               Delete (in tree)",
  "    r               Rename (in tree)",
  "",
  "  HARPOON (pin favorite files)",
  "    <leader>a        Pin current file      (Space a)",
  "    Ctrl+E          Open pinned files menu",
  "    <leader>1-5      Jump to pinned file 1-5",
  "",
  "  BUFFERS (open files)",
  "    Shift+H / Shift+L   Previous / Next buffer",
  "    <leader>bd       Close current buffer",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  SPLITS & WINDOWS",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    :vsp             Vertical split (side by side)",
  "    :sp              Horizontal split (top/bottom)",
  "    Ctrl+h/j/k/l    Move between splits (works with tmux too!)",
  "    Ctrl+Up/Down     Resize height",
  "    Ctrl+Left/Right  Resize width",
  "    Ctrl+w q         Close split",
  "    Ctrl+w o         Close all other splits",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  CODE INTELLIGENCE (LSP)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    gd              Go to definition",
  "    gr              Find all references",
  "    gI              Go to implementation",
  "    K               Hover documentation (press K on any symbol)",
  "    <leader>ca      Code action (fixes, refactors)",
  "    <leader>cr      Rename symbol (project-wide)",
  "    <leader>cf      Format file",
  "    <leader>ch      Toggle inlay hints",
  "    [d / ]d          Previous / Next diagnostic (error/warning)",
  "    <leader>e       Show diagnostic in float",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  COMPLETION (Insert mode)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    Ctrl+n / Ctrl+p  Next / Previous suggestion",
  "    Ctrl+y          Accept suggestion (recommended)",
  "    Enter           Accept (only if you selected one)",
  "    Ctrl+Space      Trigger completion manually",
  "    Ctrl+e          Dismiss completion menu",
  "    Tab / Shift+Tab  Jump snippet placeholders",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  GIT",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    <leader>tg       Open Lazygit (best git UI)   (Space t g)",
  "    <leader>gg       Git status (Fugitive)",
  "    ]h / [h          Next / Previous changed hunk",
  "    <leader>hs       Stage hunk",
  "    <leader>hr       Reset hunk",
  "    <leader>hp       Preview hunk change",
  "    <leader>hb       Show git blame for line",
  "    <leader>gd       Open diff view",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  AI / LLM TOOLS",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "  COPILOT (inline, auto-triggers while typing)",
  "    Alt+l           Accept suggestion",
  "    Alt+w           Accept word only",
  "    Alt+j           Accept line only",
  "    Alt+] / Alt+[   Next / Previous suggestion",
  "",
  "  CLAUDE CODE & CHAT",
  "    <leader>ll       Open Claude Code terminal    (Space l l)",
  "    <leader>lc       Open Copilot Chat",
  "    <leader>le       Explain code (select first)",
  "    <leader>lr       Review code",
  "    <leader>lf       Fix code",
  "    <leader>lt       Generate tests",
  "    <leader>la       CodeCompanion actions menu",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  TERMINAL",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    Ctrl+\\          Toggle floating terminal",
  "    Esc Esc         Exit terminal mode (back to Normal)",
  "    <leader>tf       Float terminal",
  "    <leader>th       Horizontal terminal",
  "    <leader>tv       Vertical terminal",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  TESTING & DEBUGGING",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "  TESTING",
  "    <leader>Tt       Run nearest test",
  "    <leader>Tf       Run all tests in file",
  "    <leader>Ta       Run all project tests",
  "    <leader>Td       Debug nearest test",
  "",
  "  DEBUGGING",
  "    <leader>db       Toggle breakpoint",
  "    <leader>dc       Continue / Start debugging",
  "    <leader>di       Step into",
  "    <leader>do       Step out",
  "    <leader>dO       Step over",
  "    <leader>dt       Terminate debug session",
  "    <leader>du       Toggle debug UI",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  GO DEVELOPMENT",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    <leader>cgt      Run Go tests",
  "    <leader>cgT      Run test at cursor",
  "    <leader>cgr      Go run",
  "    <leader>cge      Insert if err != nil",
  "    <leader>cga      Add struct tags (json)",
  "    <leader>cgc      Toggle coverage overlay",
  "    <leader>cgi      Implement interface",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  TEXT OBJECTS (use with d, c, y, v — e.g., daf = delete around function)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    af / if          Around / Inside function",
  "    ac / ic          Around / Inside class",
  "    aa / ia          Around / Inside argument",
  "    al / il          Around / Inside loop",
  "    ab / ib          Around / Inside block",
  "    ai / ii          Around / Inside conditional",
  "",
  "  Examples:  daf = delete function · cif = change inside function",
  "             yaa = yank around argument · vif = select inside function",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  COMMENTING & SURROUND",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    gcc             Comment/uncomment line",
  "    gc (visual)     Comment/uncomment selection",
  "    gsa\"            Add quotes around word (also ' ( { [)",
  "    gsd\"            Delete surrounding quotes",
  "    gsr\"'           Replace \" with '",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  TMUX (prefix = Ctrl+A)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    prefix + |       Split vertically",
  "    prefix + -       Split horizontally",
  "    Ctrl+h/j/k/l    Move between panes (no prefix!)",
  "    prefix + z       Toggle pane zoom (fullscreen)",
  "    prefix + c       New window",
  "    prefix + n / p   Next / Previous window",
  "    prefix + 1-9     Go to window by number",
  "    prefix + S       New session",
  "    prefix + o       Session picker (FZF)",
  "    prefix + d       Detach (leave running)",
  "    prefix + g       Lazygit popup",
  "    prefix + C       Claude Code popup",
  "    prefix + I       Install plugins (first time)",
  "    prefix + r       Reload config",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  LEADER KEY GROUPS (press Space and wait to see all options)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    <leader>f...     Find (files, grep, buffers, symbols, keymaps)",
  "    <leader>c...     Code (action, rename, format, Go cmds)",
  "    <leader>l...     LLM (Claude, Copilot, CodeCompanion)",
  "    <leader>g...     Git (commits, branches, status, diff)",
  "    <leader>h...     Hunks (stage, reset, preview, blame)",
  "    <leader>d...     Debug (breakpoints, step, continue)",
  "    <leader>T...     Test (run, file, all, debug)",
  "    <leader>t...     Terminal (float, horizontal, vertical, lazygit)",
  "    <leader>x...     Diagnostics / Trouble",
  "    <leader>s...     Swap arguments / Spectre search",
  "    <leader>q...     Session (restore, last, stop)",
  "    <leader>b...     Buffer (close, close all)",
  "    <leader><tab>... Tabs (new, close, last, first)",
  "    <leader>?        This cheat sheet!",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  TIPS",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "  • Press <leader> and WAIT — which-key shows all continuations",
  "  • Press <leader>fk to search ALL keymaps by name",
  "  • Use :checkhealth to diagnose issues",
  "  • Use :Mason to manage language servers and tools",
  "  • Use :Lazy to manage plugins",
  "  • Numbers work as multipliers: 5j moves 5 lines down, 3dd deletes 3 lines",
  "  • . (dot) repeats your last edit",
  "  • Ctrl+o / Ctrl+i jump to older / newer cursor positions",
  "",
}

-- Register the cheat sheet keymap directly (no plugin dependency needed)
local function open_cheatsheet()
  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, cheatsheet_lines)
  vim.bo[buf].modifiable = false
  vim.bo[buf].buftype = "nofile"
  vim.bo[buf].bufhidden = "wipe"
  vim.bo[buf].filetype = "cheatsheet"

  -- Calculate window size (90% of screen, capped)
  local width = math.min(math.floor(vim.o.columns * 0.9), 80)
  local height = math.min(math.floor(vim.o.lines * 0.85), 50)
  local row = math.floor((vim.o.lines - height) / 2)
  local col = math.floor((vim.o.columns - width) / 2)

  local win = vim.api.nvim_open_win(buf, true, {
    relative = "editor",
    width = width,
    height = height,
    row = row,
    col = col,
    style = "minimal",
    border = "rounded",
    title = " Cheat Sheet ",
    title_pos = "center",
  })

  vim.wo[win].winhl = "Normal:NormalFloat,FloatBorder:FloatBorder"
  vim.wo[win].cursorline = true
  vim.wo[win].wrap = false

  local close = function()
    if vim.api.nvim_win_is_valid(win) then
      vim.api.nvim_win_close(win, true)
    end
  end
  vim.keymap.set("n", "q", close, { buffer = buf, nowait = true })
  vim.keymap.set("n", "<Esc>", close, { buffer = buf, nowait = true })
  vim.keymap.set("n", "<leader>?", close, { buffer = buf, nowait = true })
end

vim.keymap.set("n", "<leader>?", open_cheatsheet, { desc = "Open cheat sheet" })

-- Return empty table so lazy.nvim doesn't complain about this file
return {}
