-- =============================================================================
-- Cheat Sheet — Quick reference floating window (<leader>?)
-- =============================================================================
--
-- Opens a searchable, scrollable cheat sheet in a floating window.
-- Designed for someone learning Neovim from scratch.
-- =============================================================================

local cheatsheet_lines = {
  "╔══════════════════════════════════════════════════════════════════════════╗",
  "║                     NEOVIM & TMUX CHEAT SHEET                         ║",
  "║          Open: <leader>?  (Space ?)  ·  Close: q or <Esc>             ║",
  "║                       Search inside: / pattern                        ║",
  "╚══════════════════════════════════════════════════════════════════════════╝",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  KEY NOTATION (how to read key combos in this sheet and in nvim docs)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    <C-x>             Ctrl + x  (hold Ctrl, press x)",
  "    <S-x>  or  X      Shift + x  (uppercase letter)",
  "    <M-x>  or  <A-x>  Alt / Meta + x  (on Mac, the Option key)",
  "    <D-x>             Cmd + x  (Mac — rarely used in nvim)",
  "    <CR>              Enter (Carriage Return)",
  "    <Esc>             Escape",
  "    <Tab> / <S-Tab>   Tab / Shift+Tab",
  "    <Space>           Space bar",
  "    <BS>              Backspace",
  "    <leader>          Your leader key — Space, in your config",
  "",
  "  This sheet sometimes writes Ctrl+x for readability; <C-x> means the",
  "  same thing. The <...> form is what you'll see in nvim's :help docs.",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  MOVEMENT — RULE OF THUMB (pick the right tool for the distance)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    SHORT   (same line / nearby)",
  "      h j k l            One char in any direction",
  "      w / b / e          Next / Previous / End of word",
  "      f<c> / F<c>        Jump to next/prev char <c> on the line",
  "      t<c> / T<c>        Same, but stop just before <c>",
  "      ; / ,              Repeat last f/t forward / backward",
  "      0 / ^ / $          Start of line / first non-blank / end of line",
  "",
  "    MEDIUM  (visible on screen — use flash, it's the fastest)",
  "      s + 2 chars        Flash jump — type any 2 visible chars to fly there",
  "      H / M / L          Top / Middle / Bottom of visible window",
  "      { / }              Previous / Next blank-line-separated paragraph",
  "      % (on a bracket)   Jump to its matching bracket/paren/brace",
  "",
  "    LONG    (across the file / coming back from a jump)",
  "      gg / G             Top / Bottom of file",
  "      :42  or  42G       Go to line 42",
  "      Ctrl+d / Ctrl+u    Half-page down / up (cursor stays centered)",
  "      Ctrl+f / Ctrl+b    Full-page down / up",
  "      Ctrl+o / Ctrl+i    Jump to older / newer cursor position (history)",
  "      '' (two ticks)     Return to position before your last jump",
  "      '.                 Jump to location of your last edit",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  THE ABSOLUTE BASICS (you need these to survive)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "  MODES — Neovim has modes. This is the #1 concept.",
  "    Normal mode   You're here when you open nvim. Navigate & run commands.",
  "    Insert mode   Where you type text. Press i to enter, jk or Esc to leave.",
  "    Visual mode   Select text. Press v (chars), V (lines), Ctrl+v (block).",
  "    Command mode  Press : to type commands at the bottom.",
  "",
  "  OPENING & CLOSING FILES",
  "    :w              Save current file",
  "    :q              Quit (fails if unsaved changes)",
  "    :wq             Save and quit",
  "    :q!             Quit WITHOUT saving (force)",
  "    <leader>w       Save current file          (Space then w)",
  "    <leader>q       Quit                       (Space then q)",
  "    <leader>bd      Close current file/buffer   (Space then b then d)",
  "",
  "  ⚠ Don't press q alone! That starts macro recording.",
  "    If you accidentally hit q, press q again to stop, then use :q to quit.",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  MOVEMENT (Normal mode — no prefix needed)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    h j k l         Left, Down, Up, Right (or use arrow keys)",
  "    w / b            Next word / Previous word",
  "    0 / $            Start / End of line",
  "    gg / G           Top / Bottom of file",
  "    Ctrl+d / Ctrl+u  Half-page down / up (cursor stays centered)",
  "    { / }            Previous / Next paragraph",
  "    %               Jump to matching bracket",
  "    s + 2 chars      Flash jump (type 2 chars to jump anywhere visible)",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  EDITING (Normal mode)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "  ENTERING INSERT MODE",
  "    i / a            Insert before / after cursor",
  "    I / A            Insert at start / end of line",
  "    o / O            New line below / above",
  "",
  "  DELETING",
  "    x               Delete character under cursor",
  "    dd              Delete entire line",
  "    dw              Delete word",
  "    D               Delete to end of line",
  "",
  "  CHANGING (delete + enter insert mode)",
  "    cw              Change word",
  "    cc              Change entire line",
  "    C               Change to end of line",
  "    ci\"             Change inside quotes (also ci' ci( ci{ ci[)",
  "",
  "  COPY & PASTE",
  "    yy              Copy (yank) current line",
  "    Y               Copy to end of line",
  "    p / P            Paste after / before cursor",
  "    <leader>p        Paste without losing clipboard (visual mode)",
  "",
  "  UNDO & REDO",
  "    u               Undo",
  "    Ctrl+r          Redo",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  SEARCHING IN A FILE",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    /pattern         Search forward for 'pattern'",
  "    ?pattern         Search backward for 'pattern'",
  "    n               Jump to next match",
  "    N               Jump to previous match",
  "    *               Search forward for word under cursor",
  "    #               Search backward for word under cursor",
  "    :noh            Clear search highlighting",
  "",
  "  TIPS:",
  "    /\\cpattern      Case-insensitive search (\\c anywhere in pattern)",
  "    /\\Cpattern      Force case-sensitive search",
  "    :%s/old/new/g   Replace all 'old' with 'new' in file",
  "    :%s/old/new/gc  Replace with confirmation (y/n each match)",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  FINDING THINGS (Telescope — fuzzy finder)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    <leader>ff       Find files           (Space f f)",
  "    <leader>fg       Live grep (search)   (Space f g)",
  "    <leader>fb       Open buffers         (Space f b)",
  "    <leader>fr       Recent files         (Space f r)",
  "    <leader>fw       Grep word at cursor  (Space f w)",
  "    <leader>/        Search in current file",
  "    <leader>fk       Search all keymaps   (Space f k)",
  "    <leader>fh       Search help          (Space f h)",
  "",
  "  Inside Telescope:",
  "    Ctrl+j / Ctrl+k  Move selection down / up",
  "    Enter            Open file",
  "    Ctrl+s           Open in horizontal split",
  "    Ctrl+q           Send results to quickfix list",
  "    Esc              Close picker",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  FILE EXPLORER & FAST SWITCHING",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "  NEO-TREE (file explorer)",
  "    <leader>n        Toggle file tree     (Space n)",
  "    <leader>N        Reveal current file in tree",
  "    l / Enter        Open file (in tree)",
  "    h               Close folder (in tree)",
  "    a               Create new file (in tree)",
  "    d               Delete (in tree)",
  "    r               Rename (in tree)",
  "",
  "  HARPOON (pin favorite files)",
  "    <leader>a        Pin current file      (Space a)",
  "    Ctrl+E          Open pinned files menu",
  "    <leader>1-5      Jump to pinned file 1-5",
  "",
  "  BUFFERS (open files)",
  "    Shift+H / Shift+L   Previous / Next buffer",
  "    <leader>bd       Close current buffer",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  SPLITS & WINDOWS",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    :vsp  or Ctrl+w v   Vertical split (side by side)",
  "    :sp   or Ctrl+w s   Horizontal split (top/bottom)",
  "    Ctrl+h/j/k/l       Move between splits (works with tmux too!)",
  "    Ctrl+Up/Down        Resize height",
  "    Ctrl+Left/Right     Resize width",
  "    Ctrl+w =            Equalize all split sizes",
  "    Ctrl+w _            Maximize current split height",
  "    Ctrl+w |            Maximize current split width",
  "    Ctrl+w q  or :q     Close current split",
  "    Ctrl+w o            Close all other splits",
  "    Ctrl+w T            Move current split to its own tab",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  CODE INTELLIGENCE (LSP)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    gd              Go to definition",
  "    gr              Find all references",
  "    gI              Go to implementation",
  "    K               Hover documentation (press K on any symbol)",
  "    <leader>ca      Code action (fixes, refactors)",
  "    <leader>cr      Rename symbol (project-wide)",
  "    <leader>cf      Format file",
  "    <leader>ch      Toggle inlay hints",
  "    [d / ]d          Previous / Next diagnostic (error/warning)",
  "    <leader>e       Show diagnostic in float",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  COMPLETION (Insert mode)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    Ctrl+n / Ctrl+p  Next / Previous suggestion",
  "    Ctrl+y          Accept suggestion (recommended)",
  "    Enter           Accept (only if you selected one)",
  "    Ctrl+Space      Trigger completion manually",
  "    Ctrl+e          Dismiss completion menu",
  "    Tab / Shift+Tab  Jump snippet placeholders",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  GIT",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    <leader>tg       Open Lazygit (best git UI)   (Space t g)",
  "    <leader>gg       Git status (Fugitive)",
  "    ]h / [h          Next / Previous changed hunk",
  "    <leader>hs       Stage hunk",
  "    <leader>hr       Reset hunk",
  "    <leader>hp       Preview hunk change",
  "    <leader>hb       Show git blame for line",
  "    <leader>gd       Open diff view",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  AI / LLM TOOLS",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "  COPILOT (inline, auto-triggers while typing)",
  "    Alt+l           Accept suggestion",
  "    Alt+w           Accept word only",
  "    Alt+j           Accept line only",
  "    Alt+] / Alt+[   Next / Previous suggestion",
  "",
  "  CLAUDE CODE & CHAT",
  "    <leader>ll       Open Claude Code terminal    (Space l l)",
  "    <leader>lc       Open Copilot Chat",
  "    <leader>le       Explain code (select first)",
  "    <leader>lr       Review code",
  "    <leader>lf       Fix code",
  "    <leader>lt       Generate tests",
  "    <leader>la       CodeCompanion actions menu",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  RUNNING COMMANDS & TERMINAL",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "  QUICK COMMANDS (from Normal mode)",
  "    :!command        Run a shell command     (e.g. :!ls, :!go build)",
  "    :r !command      Run command & paste output into buffer",
  "    :!%              Run current file as a script",
  "    :.!command       Replace current line with command output",
  "",
  "  EMBEDDED TERMINAL",
  "    Ctrl+\\          Toggle floating terminal",
  "    Esc Esc         Exit terminal mode (back to Normal)",
  "    <leader>tf       Float terminal",
  "    <leader>th       Horizontal terminal",
  "    <leader>tv       Vertical terminal",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  TESTING & DEBUGGING",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "  TESTING",
  "    <leader>Tt       Run nearest test",
  "    <leader>Tf       Run all tests in file",
  "    <leader>Ta       Run all project tests",
  "    <leader>Td       Debug nearest test",
  "",
  "  DEBUGGING",
  "    <leader>db       Toggle breakpoint",
  "    <leader>dc       Continue / Start debugging",
  "    <leader>di       Step into",
  "    <leader>do       Step out",
  "    <leader>dO       Step over",
  "    <leader>dt       Terminate debug session",
  "    <leader>du       Toggle debug UI",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  GO DEVELOPMENT",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    <leader>cgt      Run Go tests",
  "    <leader>cgT      Run test at cursor",
  "    <leader>cgr      Go run",
  "    <leader>cge      Insert if err != nil",
  "    <leader>cga      Add struct tags (json)",
  "    <leader>cgc      Toggle coverage overlay",
  "    <leader>cgi      Implement interface",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  TEXT OBJECTS (use with d, c, y, v — e.g., daf = delete around function)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    af / if          Around / Inside function",
  "    ac / ic          Around / Inside class",
  "    aa / ia          Around / Inside argument",
  "    al / il          Around / Inside loop",
  "    ab / ib          Around / Inside block",
  "    ai / ii          Around / Inside conditional",
  "",
  "  Examples:  daf = delete function · cif = change inside function",
  "             yaa = yank around argument · vif = select inside function",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  COMMENTING & SURROUND",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    gcc             Comment/uncomment line",
  "    gc (visual)     Comment/uncomment selection",
  "    gsa\"            Add quotes around word (also ' ( { [)",
  "    gsd\"            Delete surrounding quotes",
  "    gsr\"'           Replace \" with '",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  TMUX (prefix = Ctrl+A)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "  PANES (splits within a window)",
  "    prefix + |       Split pane vertically",
  "    prefix + -       Split pane horizontally",
  "    Ctrl+h/j/k/l    Move between panes (no prefix!)",
  "    prefix + z       Toggle pane zoom (fullscreen)",
  "    prefix + x       Close (kill) current pane — confirms",
  "    prefix + H/J/K/L Resize pane (repeatable: hold prefix once, press HJKL)",
  "    prefix + space   Cycle through preset layouts",
  "    prefix + !       Break pane out into its own window",
  "    prefix + {  / }  Swap pane with previous / next",
  "",
  "  WINDOWS (tabs at the bottom of tmux)",
  "    prefix + c       New window",
  "    prefix + n / p   Next / Previous window",
  "    prefix + 1-9     Go to window by number",
  "    prefix + ,       Rename current window",
  "    prefix + &       Close (kill) current window — confirms",
  "",
  "  SESSIONS & OTHER",
  "    prefix + S       New session",
  "    prefix + o       Session picker (FZF)",
  "    prefix + d       Detach (leave running)",
  "    prefix + g       Lazygit popup",
  "    prefix + C       Claude Code popup",
  "    prefix + I       Install plugins (first time)",
  "    prefix + r       Reload config",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  LEADER KEY GROUPS (press Space and wait to see all options)",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "    <leader>f...     Find (files, grep, buffers, symbols, keymaps)",
  "    <leader>c...     Code (action, rename, format, Go cmds)",
  "    <leader>l...     LLM (Claude, Copilot, CodeCompanion)",
  "    <leader>g...     Git (commits, branches, status, diff)",
  "    <leader>h...     Hunks (stage, reset, preview, blame)",
  "    <leader>d...     Debug (breakpoints, step, continue)",
  "    <leader>T...     Test (run, file, all, debug)",
  "    <leader>t...     Terminal (float, horizontal, vertical, lazygit)",
  "    <leader>x...     Diagnostics / Trouble",
  "    <leader>s...     Swap arguments / Spectre search",
  "    <leader>q...     Session (restore, last, stop)",
  "    <leader>b...     Buffer (close, close all)",
  "    <leader><tab>... Tabs (new, close, last, first)",
  "    <leader>?        This cheat sheet!",
  "",
  "══════════════════════════════════════════════════════════════════════════",
  "  TIPS",
  "══════════════════════════════════════════════════════════════════════════",
  "",
  "  • Press <leader> and WAIT — which-key shows all continuations",
  "  • Press <leader>fk to search ALL keymaps by name",
  "  • Use :checkhealth to diagnose issues",
  "  • Use :Mason to manage language servers and tools",
  "  • Use :Lazy to manage plugins",
  "  • Numbers work as multipliers: 5j moves 5 lines down, 3dd deletes 3 lines",
  "  • . (dot) repeats your last edit",
  "  • Ctrl+o / Ctrl+i jump to older / newer cursor positions",
  "",
}

-- Register the cheat sheet keymap directly (no plugin dependency needed)
local function open_cheatsheet()
  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, cheatsheet_lines)
  vim.bo[buf].modifiable = false
  vim.bo[buf].buftype = "nofile"
  vim.bo[buf].bufhidden = "wipe"
  vim.bo[buf].filetype = "cheatsheet"

  -- Calculate window size (use most of the screen, capped for readability)
  local width = math.min(math.floor(vim.o.columns * 0.92), 110)
  local height = math.min(math.floor(vim.o.lines * 0.92), 75)
  local row = math.floor((vim.o.lines - height) / 2)
  local col = math.floor((vim.o.columns - width) / 2)

  local win = vim.api.nvim_open_win(buf, true, {
    relative = "editor",
    width = width,
    height = height,
    row = row,
    col = col,
    style = "minimal",
    border = "rounded",
    title = " Cheat Sheet ",
    title_pos = "center",
  })

  vim.wo[win].winhl = "Normal:NormalFloat,FloatBorder:FloatBorder"
  vim.wo[win].cursorline = true
  vim.wo[win].wrap = false

  local close = function()
    if vim.api.nvim_win_is_valid(win) then
      vim.api.nvim_win_close(win, true)
    end
  end
  vim.keymap.set("n", "q", close, { buffer = buf, nowait = true })
  vim.keymap.set("n", "<Esc>", close, { buffer = buf, nowait = true })
  vim.keymap.set("n", "<leader>?", close, { buffer = buf, nowait = true })

  -- Close the float when focus moves away (e.g. Ctrl+h/j/k/l navigation)
  vim.api.nvim_create_autocmd("WinLeave", {
    buffer = buf,
    once = true,
    callback = close,
  })
end

vim.keymap.set("n", "<leader>?", open_cheatsheet, { desc = "Open cheat sheet" })

-- Return empty table so lazy.nvim doesn't complain about this file
return {}
